#
# This file is generated by ModusToolbox during the 'make getlibs' operation
# Any edits to this file will be lost the next time the library manager is run or
# the next time 'make getlibs' is run.
#
# List of local libraries



# The search paths for the included middleware
SEARCH_btsdk-host-apps-bt-ble=../mtb_shared/wiced_btsdk/tools/btsdk-host-apps-bt-ble/release-v4.2.1
SEARCH_TARGET_CYW920820M2EVB-01=../mtb_shared/wiced_btsdk/dev-kit/bsp/TARGET_CYW920820M2EVB-01/release-v4.2.1
SEARCH_20820A1=../mtb_shared/wiced_btsdk/dev-kit/baselib/20820A1/release-v4.2.1
SEARCH_btsdk-common=../mtb_shared/wiced_btsdk/dev-kit/libraries/btsdk-common/release-v4.2.1
SEARCH_btsdk-include=../mtb_shared/wiced_btsdk/dev-kit/btsdk-include/release-v4.2.1
SEARCH_btsdk-tools=../mtb_shared/wiced_btsdk/dev-kit/btsdk-tools/release-v3.3.0
SEARCH_btsdk-utils=../mtb_shared/wiced_btsdk/tools/btsdk-utils/release-v4.2.0
SEARCH_core-make=../mtb_shared/core-make/release-v1.9.1

# Search libraries added to build
SEARCH+=$(SEARCH_btsdk-host-apps-bt-ble)
SEARCH+=$(SEARCH_TARGET_CYW920820M2EVB-01)
SEARCH+=$(SEARCH_20820A1)
SEARCH+=$(SEARCH_btsdk-common)
SEARCH+=$(SEARCH_btsdk-include)
SEARCH+=$(SEARCH_btsdk-tools)
SEARCH+=$(SEARCH_btsdk-utils)
SEARCH+=$(SEARCH_core-make)

-include $(CY_INTERNAL_APP_PATH)/importedbsp.mk
COMPONENTS += MW_BTSDK_HOST_APPS_BT_BLE
COMPONENTS += MW_TARGET_CYW920820M2EVB_01
COMPONENTS += MW_20820A1
COMPONENTS += MW_BTSDK_COMMON
COMPONENTS += MW_BTSDK_INCLUDE
COMPONENTS += MW_BTSDK_TOOLS
COMPONENTS += MW_BTSDK_UTILS
COMPONENTS += MW_CORE_MAKE
